### PR TITLE
Prettier cricles, powered by css-awesomeness

### PR DESCRIPTION
**Pull request by dstaley**

### CODE REVIEW

**Comment by paddycarver** [comment]
Is it just me, or are these.... really grainy?

EDIT: grainy = pixelated.

**Comment by carimura** [comment]
Hey Guys,

Suggestion: if you want input from others, it would help to include a quick snapshot of the changes associated with a pull request (or ticket). Alternatively, a link to staging with the change if it's obvious works as well.

**Comment by paddycarver** [comment]
Gotta get @dstaley set up with staging push access. But yeah, screenshots of before/after are a good idea.

Before:
Before

After:
After

With that side-by-side comparison, I guess they aren't more pixelated than the old ones. The main difference is the subtle gradient and the fact that they're pure CSS.

**Comment by frommww** [comment]
The after color is better because it's less of an "alert" (it bothers me that we use red-red so often in our interface, especially it seems in the dev center).

This second red is also closer to the brand background red (ie. background gears) which helps with the second "meta" point below.

Which is that as some point it would be nice to get our design language more unified including 1) the use of red, yellow, green for status/alerts/etc. 2) the base brand color, 3) service colors (if we continue using them beyond logo), and then accent colors.

**Comment by paddycarver** [comment]
Listen, I didn't choose red as the only colour in our logo or branding. ;)

**Comment by paddycarver** [comment]
Sounds like everyone's in favour of this. I'll merge it in.

**Pull request merged**
