### PR TITLE
fixes #330

### LINKED ISSUE #330: Add security group id to docs
To here: http://dev.iron.io/worker/reference/security/#security_groups_and_ip_ranges

id: sg-0d500c64

### PR DESCRIPTION
**Pull request by borgified**
im guessing this is what you mean by adding the security group id

### CODE REVIEW

**Comment by treeder** [comment]
The security group id is `simple_worker_sg` (i believe).

**Comment by featalion** [comment]
A lot of people asked about security group string already defined at [DevCenter](http://dev.iron.io/worker/reference/environment/#security_groups_and_ip_ranges)

**Comment by borgified** [comment]
Ah... didn't realize similar information existed in two places:

http://dev.iron.io/worker/reference/security/#security_groups_and_ip_ranges
http://dev.iron.io/worker/reference/environment/#security_groups_and_ip_ranges

The 1st link mentions: "Please note that this security group only works in the US regions."

Should the information about security_groups_and_ip_ranges in 2nd link be copied over to the first link?
Should the note about only working in the US regions be included in the 2nd link?

**Comment by featalion** [comment]
I assume we can remove section at second link, but definitely need link to security page on navigation menu in section Reference.

**Comment by borgified** [comment]
awaiting confirmation of removing security_groups_and_ip_ranges section at second link.
correct to assume 2nd link has the "better/more current" information?

**Comment by carimura** [comment]
cc @featalion 

hey @borgified send an address to chad[at]iron.io and we'll get you off a t-shirt!

**Comment by featalion** [comment]
Maybe good to keep it in both sections, but add the link to security section at environment section.
I will do.

**Comment by featalion** [comment]
merged and improved, #355

**Pull request closed without merging**
