### PR TITLE
Docs for running IronMQ Lite.

### PR DESCRIPTION
**Pull request by treeder**

### CODE REVIEW

**Comment by arschles** [comment]
@treeder can we use these in place of https://github.com/iron-io/docs/blob/gh-pages/mq/3/on-premise/installation/index.md#manual? seems like they achieve the same goal

**Comment by treeder** [comment]
@arschles I think being able to setup IronMQ HA/Cluster with auth and everything is still important. IronMQ Lite is a bit of a different animal.

**Comment by arschles** [comment]
@treeder cluster ya but there's [single node instructions](https://github.com/iron-io/docs/blob/gh-pages/mq/3/on-premise/installation/index.md#install-and-start-single-instance) in there. would be nice to use these instead b/c those instructions go through setting up auth, etc...

**Comment by treeder** [comment]
Lite doesn't have auth or anything, that's why it's a different process.

**Comment by rdallman** [comment]
idk what to do about auth. it seems like an inconvenience for the on
premise stuff so far... and even if they do want it they really only want
that sweet hud-e action

**Comment by arschles** [comment]
@treeder and I figured we'd link to lite on the onprem docs so people can at least try it

**Comment by carimura** [comment]
Ya damn this is going to be confusing... we now have Lite, binary, single server, Docker, Terraform, HA, oh my!

I really think Lite and "Single Server" should merge into one thing and _still_ get the single command installation. That way we can have Lite and HA, or Lite and Cluster, or whatever.

**Comment by arschles** [comment]
@carimura gonna get rid of binary. here's how I think it should look in on prem docs, split into multiple pages (manual single, terraform, manual HA are all on one big page right now)
- Single server
  - lite (`docker run`) - good for local testing, etc...
  - manual setup (`docker run` + auth setup) - good for staging envs
- HA - both good for prod
  - terraform
  - manual (`docker run` + ...)

can make lite a good lead into the other 3. hopefully saying when/why to use each will help w confusion

thoughts?

**Comment by carimura** [comment]
Ya I think that's closer for sure. This is still a discussion we're having internally so I'd say roll with that for now. I can see things going towards soemthing like:

1) IronMQ Lite (dev/test/stage no auth no ui)
2) IronMQ Standard (Single server w/ auth w/ ui)
3) IronMQ Enterprise/HA/Other (Clustered for serious apps)

Each of those would have their own set of deployment options.. ideallly all of them super easy and elegant.

**Comment by arschles** [comment]
@treeder ready to merge?

**Comment by treeder** [comment]
Is now, but hold on this one until we're ready.

**Comment by arschles** [comment]
k

**Comment by carimura** [comment]
You guys can roll it out if you want.

**Comment by carimura** [comment]
We'll need to evaluate product strategy soon though.

**Comment by Stephenitis** [comment]
@treeder can we update this branch?

**Comment by treeder** [comment]
This is on hold for now...

**Pull request closed without merging**
