### PR TITLE
Remove timeout and http 202 handling from push queues

### PR DESCRIPTION
**Pull request by alex-litvak**

### CODE REVIEW

**Comment by alex-litvak** [comment]
@rdallman Can you take a look please?

**Comment by rdallman** [comment]
I think we still aim to support 202? even if it's a bad protocol, I don't think we can break API now. are you removing this because it's buggy? code has it implemented, maybe it just doesn't work.

**Comment by alex-litvak** [comment]
I'm removing it because it's buggy and confusing our customers

**Comment by rdallman** [comment]
could you discuss with us in slack how exactly it is buggy? links to
intercom tickets, etc. would be great (this repo is public, so not here)

**Pull request merged**
