### PR TITLE
Task scheduling optional parameters: +timeout, -delay, -task_delay

### PR DESCRIPTION
**Pull request by vasilev**
Added task scheduling optional parameters description to worker api reference: timeout, delay, task_delay .

### CODE REVIEW

**Comment by vasilev** [comment]
@Stephenitis , could you please review ?

**Comment by treeder** [comment]
Please remove delay and task_delay.

**Comment by vasilev** [comment]
'delay' and 'task_delay' removed.
@Stephenitis , could you please take a look ?

**Comment by vasilev** [comment]
:thumbsup:

**Pull request merged**
