### PR TITLE
fixes #223,#330,#357

### LINKED ISSUE #223: Update API Errors : 403 - Project suspended / resource limits
Update the API specs to include 403 error response for project suspended, resources limits.

Ken Fromm
question:
what's the http 4xx response if someone hits their usage limit? Didn't see it called out in the api page.

Michael Fellinger
@ken afaict it's 403
with body of "Your project has been suspended"

you might wanna ask @evan though, in case i'm missing something
but it looks like that's used across all APIs

Evan Shaw
That sounds right

Ken Fromm
great. thanks.

### PR DESCRIPTION
**Pull request by borgified**

### CODE REVIEW

**Comment by Stephenitis** [comment]
@borgified sorry this fell behind, can you fix conflicts so I can merge them in?

**Comment by borgified** [comment]
Sure np. It's been a while so it'll take me some time to get reacquainted. I'll get it done over weekend. 

-- JC

**Comment by borgified** [comment]
Wow, hang on, before you merge, pls allow me to redo everything. I'll just start over and do a clone of what you've got currently then step through my changes so that everything's a lot cleaner.

**Comment by borgified** [comment]
hi @Stephenitis i've finished cleaning this up.
i have created a new fork your repo and stuck it here: https://github.com/borgified/iron-io
6726626c56e2f1ece4f7e1dfbe9db3f629709a6c is for #330
bfeb8cacc3ad3df829e48176f2e7cb9311478c08 is for #223 
ignoring #357 because i see that those changes aren't needed any longer

unfortunately github wont let me create multiple forks of the same repository so my new "fork" lacks those nice features to generate a pull request for you, so hopefully it's not too much trouble for you to pick up from my repo.

if it's ok with you, i can delete my "docs" repo then fork your repo again to regain the github functionalities, but i'll do that after all this is sorted out.

thanks and merry xmas!

**Comment by treeder** [comment]
This good @Stephenitis ?

**Comment by borgified** [comment]
gonna redo all this, cleaner this time

**Pull request closed without merging**
