### PR TITLE
Add clear queue endpoint

### PR DESCRIPTION
**Pull request by edsrzf**
This is a proposal. If we like it, merge it and I'll implement it.

### CODE REVIEW

**Comment by paddycarver** [comment]
I'm in favour. @treeder?

**Comment by frommww** [comment]
should there be some double authentication mechanism to do this? Not a "are you sure response" :) but something that provides an additional level of security (a separate token registered specifically for clearing/deleting queues).

**Comment by frommww** [comment]
or alternatively, it could be archived for a certain period of time (but then that would mean an unarchive capability would be needed).

**Comment by edsrzf** [comment]
I wondered about that too, Ken. Either you're using a client library and explicitly calling some kind of "clear_messages" method or you're accessing the API directly. My feeling is that in either case it takes enough thought to access this functionality that accidents should be rare.

On the other hand, if we add a button to clear a queue via HUD, I definitely think there should be some kind of "are you sure?" It's a lot easier to fat-finger a button on a web page than to accidentally write code that clear your queue.

**Comment by treeder** [comment]
@edsrzf let's deploy this, then we can merge this.

**Comment by edsrzf** [comment]
This feature has been merged into IronMQ. I updated for a minor change in how I implemented it. ("msg" is "Cleared" instead of "Deleted")

**Pull request merged**
