### PR TITLE
added column to designate default versions of undeclared

### PR DESCRIPTION
**Pull request by Stephenitis**
ironworker environment iron io dev center 2014-04-30 17-19-08 2014-04-30 17-19-13

### CODE REVIEW

**Comment by carimura** [comment]
ehh, seems a little odd to me. Can't we just list all the default versions somewhere?

**Comment by carimura** [comment]
Or better yet put an \* next to the default version and then put a note below that says "\* Default version if stack not selected"

**Comment by Stephenitis** [comment]
I concur.

On Wed, Apr 30, 2014 at 10:53 PM, Chad Arimura notifications@github.comwrote:

> Or better yet put an \* next to the default version and then put a note
> below that says "\* Default version if stack not selected"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iron-io/docs/pull/403#issuecomment-41883107
> .

## 

Stephen Nguyen
Developer Evangelist, Iron.io http://www.iron.io/
703-975-5863 | stephen@iron.io
http://www.linkedin.com/in/stephenhnguyen/ http://www.github.com/stephenitis
  http://www.twitter.com/stephenitis

Developers <3 Iron.io! <https://twitter.com/getiron/favorites>

**Comment by Stephenitis** [comment]
ironworker environment iron io dev center 2014-04-30 23-42-54 2014-04-30 23-42-56

**Pull request merged**
